version: '3.10'

services:
  db:
    image: postgres:16.0-alpine3.17
    restart: always
    volumes:
      - postgres_data:$PGDATA
    env_file:
      - .env
    ports:
      - "5432:5432"

  theater:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db

volumes:
  postgres_data:
